name: 'Terraform Apply - Azure IAM'

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  terraform-apply:
    runs-on: ubuntu-latest

    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.4.6

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve

  activate-pim:
    needs: terraform
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Microsoft Graph PowerShell SDK
        run: Install-Module -Name Microsoft.Graph -Force -Scope CurrentUser
        shell: pwsh

      - name: Run PIM Activation Script
        run: |
          pwsh -File ./scripts/activate_pim_role.ps1
        shell: pwsh
